version: 0.2

phases:
  install:
    commands:
      - echo "hello install"
      - echo "codebuild ID is ${CODEBUILD_BUILD_ID}"
      - echo "commit ID is ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "repo url is ${CODEBUILD_SOURCE_REPO_URL}"
      - echo "source version is ${CODEBUILD_SOURCE_VERSION}"
      - echo "cb webhook previous commit is ${CODEBUILD_WEBHOOK_PREV_COMMIT}"
      - echo "cb webhook trigger is ${CODEBUILD_WEBHOOK_TRIGGER}"
      - ls -lrth *
  build:
    commands:
      - echo "hello build"
artifacts:
  files:
    - '**/*'