version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    commands:
      - echo "hello install"
      - echo "codebuild ID is ${CODEBUILD_BUILD_ID}"
      - echo "commit ID is ${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - echo "repo url is ${CODEBUILD_SOURCE_REPO_URL}"
      - echo "source version is ${CODEBUILD_SOURCE_VERSION}"
      - ls -alrth *
      - git tag -l      
  build:
    commands:
      - echo "hello build"
      - ./codebuild-git-wrapper.sh https://github.com/Amit-Naudiyal/CodeDeployGitHubDemo.git master
      - ls -alrth *
      - git tag -l

artifacts:
  files:
    - '**/*'